const dashboardActionTypes = {
  GET_POSTS_REQUESTED: "GET_POSTS_REQUESTED",
  GET_POSTS_FAILED: "GET_POSTS_FAILED",
  GET_POSTS_SUCCEEDED: "GET_POSTS_SUCCEEDED",
  GET_POST_DETAILS: "GET_POST_DETAILS",
  GET_POST_SUCCEEDED: "GET_POST_SUCCEEDED",
  GET_POST_FAILED: "GET_POST_FAILED",
};
export default dashboardActionTypes;
