const loginActionType = {
  SETEMIAL: "SETEMIAL",
  SETPASSWORD: "SETPASSWORD",
  SETEMIALERROR: "SETEMAILERROR",
  SETPASSWORDERROR: "SETPASSWORDERROR",
  SETISLOGGEDIN: "SETISLOGGEDIN",
  USER_AUTH_REQUESTED: "USER_AUTH_REQUESTED",
  USER_AUTH_SUCCEEDED: "USER_AUTH_SUCCEEDED",
  USER_AUTH_FAILED: "USER_AUTH_FAILED",
};
export default loginActionType;
