const signupActionType = {
  SETEMIAL: "SETEMIAL",
  SETPASSWORD: "SETPASSWORD",
  SETEMIALERROR: "SETEMAILERROR",
  SETPASSWORDERROR: "SETPASSWORDERROR",
  SETUSERNAME: "SETUSERNAME",
  SETUSERNAMEERROR: "SETUSERNAMEERROR",
  SETNAME: "SETNAME",
  SETNAMEERROR: "NAMEERROR",
  SETCHECKBOX: "CHECKBOX",
  SETCHECKBOXERRROR: "CHECKBOXERROR",
  USER_SIGNUP_REQUESTED: "USER_SIGNUP_REQUESTED",
  USER_SIGNUP_SUCCEEDED: "USER_SIGNUP_SUCCEEDEED",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",
};
export default signupActionType;
